"""Add user_type to User model

Revision ID: aba5f91816d7
Revises: 
Create Date: 2025-06-21 14:54:13.879629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba5f91816d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_specification', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('product_specification_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_type')

    with op.batch_alter_table('product_specification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('product_specification_ibfk_1'), 'product', ['product_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
